name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  preview_branch: gh-pages-preview
  production_branch: gh-pages-production

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Deploy to Preview Environment
      uses: actions/github-pages@v3
      env:
        GITHUB_PAGES_BRANCH: ${{ env.preview_branch }}
        PUBLISH_DIR: ./www
      with:
        cname: preview.example.com

  deploy-production:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and Deploy to Production Environment
      uses: actions/github-pages@v3
      env:
        GITHUB_PAGES_BRANCH: ${{ env.production_branch }}
        PUBLISH_DIR: ./www
      with:
        cname: production.example.com
